server:
    port: 8081
spring:
    mail:
        host: <mail-smtp-host>
        port:  587
        username: <username>
        password: <password>
        max-attempts: 4         # Custom Configuration
        backoff-delay: 5000     # Custom Configuration
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    kafka:
        bootstrap-servers: localhost:9092
        topic: mail             # Custom Configuration
        consumer:
            auto-offset-reset: earliest
            group-id: mail